WebSite/Areas/Administration/Models/ViewModels/Users/CreateViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Areas.Administration.Models.ViewModels.Users
{
    public class CreateViewModel
    {
        #region Properties

        public IEnumerable<SelectListItem> ProfilesList;
        public IEnumerable<SelectListItem> DepartmentsList;
        public IEnumerable<SelectListItem> ShiftsList;
        public IEnumerable<SelectListItem> CulturesList;
        public bool IsModal;
        public string Search;

        #endregion

        public CreateViewModel()
        {
            ProfilesList = new SelectList(new List<Profile>());
            DepartmentsList = new SelectList(new List<Department>());
            ShiftsList = new SelectList(new List<ShiftsMaster>());
            CulturesList = new SelectList(new List<Catalog>());
            IsModal = false;
            Search = "";
        }
    }
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/AddNewRuleModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class AddNewRuleModel
    {
        public IEnumerable<SelectListItem> _ComparatorType;
        public IEnumerable<SelectListItem> _DatePart;
        public int FormatLoopRuleTempID { get; set; }
        public AddNewRuleModel()
        {
            _ComparatorType = new SelectList(new List<Catalog>());
            _DatePart = new SelectList(new List<Catalog>());
            FormatLoopRuleTempID = 0;
        }
    }
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/CreateViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebSockets;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class CreateViewModel
    {
        public FormatsEntity EntityFormat { get; set; }
        public int FormatID { get; set; }
        public List<EntityField> _CustomFieldsList;
        public List<FormatGenericDetailTemp> _FormatGenericDetail;
        public List<CatalogDetailTemp> _CatalogPhase;
        public List<FormatAccessTemp> _FormatAccessTemp;
        public List<User> _UserList;
        public List<FormatsLoopsRulesTemp> _FormatsLoopsRulesTemp;
        public IEnumerable<SelectListItem> FacilityList;
        public PDFFile PDFFile { get; set; }
        public Guid TransactionID { get; set; }
        public string PathToShow { get; set; }

        public List<PDFFilesDetail_TEMP> _PDFAdditionalFields { get; set; }
        public List<PDFFilesDetail_TEMP> _PDFDetailFields { get; set; }
        public List<PDFFilesDetail_TEMP> _PDFConfigurationSignature { get; set; }
        public IEnumerable<SelectListItem> _FontList { get; set; }
        public List<Catalog> _FontListFE { get; set; }
        public List<Catalog> _FontColorList { get; set; }
        public List<Catalog> _ValueToShow { get; set; }
        public List<Catalog> _ShowWhen { get; set; }
        
        public CreateViewModel()
        {
            EntityFormat = new FormatsEntity();
            FacilityList = new SelectList(new List<Facility>());
            _CustomFieldsList = new List<EntityField>();
            _FormatGenericDetail = new List<FormatGenericDetailTemp>();
            _CatalogPhase = new List<CatalogDetailTemp>();
            _FormatAccessTemp = new List<FormatAccessTemp>();
            _UserList = new List<User>();
            _FormatsLoopsRulesTemp = new List<FormatsLoopsRulesTemp>();
            FormatID = 0;
            PDFFile = new PDFFile();
            PathToShow = "";
            _PDFAdditionalFields = new List<PDFFilesDetail_TEMP>();
            _PDFDetailFields = new List<PDFFilesDetail_TEMP>();
            _FontList = new SelectList(new List<Catalog>());
            _FontColorList = new List<Catalog>();
            _FontListFE = new List<Catalog>();
            _PDFConfigurationSignature = new List<PDFFilesDetail_TEMP>();
        }
    }
   
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/IndexViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class IndexViewModel
    {
        public List<FormatsEntity> FormatList { get; set; }
        public IndexViewModel()
        {
            FormatList = new List<FormatsEntity>();
        }
    }
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/MoNewApproverModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class MoNewApproverModel
    {
        public IEnumerable<SelectListItem> _SelectListDepartments;
        public IEnumerable<SelectListItem> _SelectListConfiguracion;
        public IEnumerable<SelectListItem> _SelectListPosition;
        public IEnumerable<SelectListItem> _SelectListUoM;
        public bool IsEdit;
        public bool ApproveAfter;
        public int FormatLoopFlowTempID;
        public int FormatLoopFlowApproverTempID;
        public int UserID;
        public string UserName;
        public MoNewApproverModel()
        {
            _SelectListDepartments = new SelectList(new List<Department>());
            _SelectListConfiguracion = new SelectList(new List<CatalogDetail>());
            _SelectListPosition = new SelectList(new List<CatalogDetail>());
            _SelectListUoM = new SelectList(new List<CatalogDetail>());
            IsEdit = false;
            ApproveAfter = false;
            FormatLoopFlowTempID = 0;
            FormatLoopFlowApproverTempID = 0;
            UserID = 0;
            UserName = "";
        }
    }
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/MoNewRuleModel.cs
using Core.Entities;
using DocumentFormat.OpenXml.Bibliography;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class MoNewRuleModel
    {
        public List<CatalogDetailTemp> _CatalogDetailTemp;
        public string RuleName;
        public bool IsEdit;
        public int FormatLoopRuleTempID;
        public MoNewRuleModel()
        {
            _CatalogDetailTemp = new List<CatalogDetailTemp>();
            RuleName = "";
            IsEdit = false;
            FormatLoopRuleTempID = 0;
        }
    }
}

WebSite/Areas/eRequest/Models/ViewModels/Formats/PDFConfigurationModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Areas.eRequest.Models.ViewModels.Formats
{
    public class PDFConfigurationModel
    {
        public List<PDFFilesDetail_TEMP> _PDFAdditionalFields { get; set; }
        public IEnumerable<SelectListItem> _FontList { get; set; }
        public IEnumerable<SelectListItem> _FontColorList { get; set; }
        public PDFConfigurationModel()
        {
            _PDFAdditionalFields = new List<PDFFilesDetail_TEMP>();
            _FontList = new SelectList(new List<Catalog>());
            _FontColorList = new SelectList(new List<Catalog>());
        }
    }
}

WebSite/Areas/eRequest/Controllers/FormatsController.cs
using Core.Entities;
using Core.Entities.Utilities;
using Core.Service;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.DirectoryServices;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Areas.eRequest.Models.ViewModels.Formats;
using WebSite.Models;
using WebSite.Utilities;
using static WebSite.Models.StaticModels;

namespace WebSite.Areas.eRequest.Controllers
{
    public class FormatsController : BaseController
    {
        // GET: eRequest/Formats
        public ActionResult Index()
        {
            var model = new IndexViewModel();
            try
            {
                model.FormatList = FormatsService.FormatsList("", "", BaseGenericRequest);
            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView(model);
            }

            return View(model);
        }
        public ActionResult SearchFormat(string FormatName, string Approver)
        {
            IndexViewModel model = new IndexViewModel();
            string viewPath = "~/Areas/eRequest/Views/Formats/_Tbl_Formats.cshtml";

            try
            {
                var UserAccess = RequestService.GetUserAccessToeRequest(BaseGenericRequest);
                model.FormatList = FormatsService.FormatsList(FormatName, Approver, BaseGenericRequest);

            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
                return View(model);
            }

            return PartialView(viewPath, model.FormatList);
        }
        public ActionResult Create(int? FormatID)
        {
            var model = new CreateViewModel();
            Guid TransactionID = Guid.NewGuid();
            GenericReturn result = new GenericReturn();
            model.TransactionID = TransactionID;
            string ErrorMessage;
            try
            {
                var eReqFieldConf = vw_CatalogService.List4Select("eReq_FieldConfList", BaseGenericRequest, true);
                if (FormatID != null)
                {
                    model.FormatID = FormatID.ToInt();
                    model.EntityFormat = RequestService.GetFormat4ID(FormatID.ToInt(), BaseGenericRequest);
                    model._UserList = FormatsService.UsersFacilitiesPermission(BaseGenericRequest.FacilityID.ToString(), BaseGenericRequest);
					int CatalogID = MiscellaneousService.Catalog_GetID(VARG_FacilityID, "FlowPhase", out ErrorMessage);                    result = FormatsService.FormatGenericDetailTempInsert(FormatID.ToInt(), TransactionID, BaseGenericRequest);
                    model.FacilityList = new SelectList(RequestService.GetFacility(BaseGenericRequest), "FacilityID", "FacilityName", BaseGenericRequest.FacilityID);

                    PDFFile PDFData = PDFFileService.PDFFiles_GetPDFDetail(FormatID.ToInt(), BaseGenericRequest);

                    if (PDFData != null)
                    {
                        model.PDFFile = PDFData;
                        model._PDFAdditionalFields = FormatsService.PDFFilesDetail_TEMP_List4Header(TransactionID, PDFData.FileID, BaseGenericRequest);
                        model._PDFDetailFields = FormatsService.PDFFilesDetail_TEMP_List4Detail(TransactionID, PDFData.FileID, BaseGenericRequest);
                        model._PDFConfigurationSignature = FormatsService.PDFFilesDetail_TEMP_List4Signatures(TransactionID, PDFData.FileID, BaseGenericRequest);
                        model._FontList = new SelectList(vw_CatalogService.List("eReq_Fonts", BaseGenericRequest), "ValueID", "DisplayText");
                        model._FontListFE = vw_CatalogService.List("eReq_Fonts", BaseGenericRequest);
                        model._FontColorList = vw_CatalogService.List("eReq_FontColor", BaseGenericRequest);
                        model._ValueToShow = vw_CatalogService.List("PDF_Value_To_Show", BaseGenericRequest);
                        model._ShowWhen = vw_CatalogService.List("PDF_Show_When", BaseGenericRequest);
                    }
                    if (result.ErrorCode == 0)
                    {
                        model._FormatGenericDetail = FormatsService.FormatGenericDetailList(FormatID.ToInt(), TransactionID, BaseGenericRequest);
                        model._CatalogPhase = CatalogDetailService.List4FormatPhase(CatalogID, FormatID.ToString(), TransactionID, BaseGenericRequest);
                        model._FormatAccessTemp = FormatsService.FormatAccessTemp_List4Transaction(FormatID.ToInt(), TransactionID, BaseGenericRequest);
                        model._FormatsLoopsRulesTemp = FormatsService.FormatsLoopsRulesTemp_List(TransactionID, BaseGenericRequest.FacilityID, BaseGenericRequest);

                    }
                    if (eReqFieldConf != null)
                    {
                        if (eReqFieldConf.Count == 1)
                        {
                            var SystemModuleTag = eReqFieldConf[0].ValueID;
                            var EntityIndicator = MiscellaneousService.Catalog_GetDetailID(VARG_FacilityID, "SystemEntities", "eReqFormat", out ErrorMessage);
                            model._CustomFieldsList = RequestService.FieldsConfigurationList(FormatID.ToInt(), EntityIndicator, SystemModuleTag, BaseGenericRequest);
                        }
                    }
                }
                else
                {

                }

            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(model);
            }
            return View(model);
        }
        public ActionResult TableFormatDetail(int FormatID, Guid TransactionID)
        {
            string ViewPath = "~/Areas/eRequest/Views/Formats/_Tbl_DetailFields.cshtml";
            var model = new List<FormatGenericDetailTemp>();
            try
            {
                model = FormatsService.FormatGenericDetailList(FormatID.ToInt(), TransactionID, BaseGenericRequest);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e.ToString();
            }

            return PartialView(ViewPath, model);
        }

        public JsonResult GetModalNewField()
        {
            ModalAddFieldViewModal model = new ModalAddFieldViewModal();
            GenericReturn result = new GenericReturn();
            string ViewPath = "~/Areas/eRequest/Views/Formats/_Mo_NewField.cshtml";
            model.Title = @Resources.Request.lbl_AddFormatFields;

            try
            {
                model.ParameterList = new SelectList(vw_CatalogService.List4Select("AdditionalFields_DataType", BaseGenericRequest, true), "CatalogDetailID", "DisplayText");
                model.CatalogsList = new SelectList(vw_CatalogService.List4Formats(BaseGenericRequest, true), "CatalogTag", "CatalogName");
                result.ErrorCode = 0;
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString(),
                View = RenderRazorViewToString(ViewPath, model)
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveTranslation(string Tag, string DescriptionEN, string DescriptionES)
        {
            GenericReturn result = new GenericReturn();
            try
            {
                result = FormatsService.TranslationDetaulUpdate(Tag, DescriptionEN, DescriptionES, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult FormatAccessTempInsert(int FormatID, Guid TransactionID, string FacilityID, string UserListID)
        {
            GenericReturn result = new GenericReturn();
            try
            {
                result = FormatsService.FormatAccessTempInsert(FormatID, TransactionID, FacilityID, UserListID, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString()
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult FormatAccessTempDelete(int FormatAccessTempID)
        {
            GenericReturn result = new GenericReturn();
            try
            {
                result = FormatsService.FormatAccess_TEMP_Delete(FormatAccessTempID, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,

WebSite/Areas/eRequest/Views/Formats/_Mo_NewDetailField.cshtml
@model WebSite.Areas.eRequest.Models.ViewModels.Formats.ModalAddDetailFieldViewModal
<div id="mo_NewDetailField" class="modal fade" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sm" style="width: 500px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-2" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title">@Model.Title</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <label class="control-label" for="Name">@Resources.Request.lbl_Name</label>
                        <div class="form-group">
                            <table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped" id="tbl_traductiondetail">
                                <thead>
                                    <tr class="font-size-sm bg-primary">
                                        <th>@Resources.Request.lbl_Languague</th>
                                        <th>@Resources.Request.lbl_Name</th>
                                    </tr>
                                </thead>
                                <tr class="font-size-sm">
                                    <td>@Resources.Common.lbl_English</td>
                                    <td>
                                        <input type="text" id="DetailTranslationEN" value="@Model.EnglishName" maxlength="100" class="form-control max-lenght" />
                                    </td>
                                </tr>
                                <tr class="font-size-sm">
                                    <td>@Resources.Common.lbl_Spanish</td>
                                    <td>
                                        <input type="text" id="DetailTranslationES" value="@Model.SpanishName" maxlength="100" class="form-control max-lenght" />
                                    </td>
                                </tr>
                                <tbody class="ui-state-default sortable">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row hidden">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label class="control-label">@Resources.Common.lbl_Detail</label>
                            @Html.TextArea("txt_detail_description", Model.FormatDetail.Description, new { @class = "form-control max-length", @autocomplete = "off", @maxlength = "255", @rows = "5" })
                            <br />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <label class="control-label">@Resources.Request.lbl_Type</label>
                            @Html.DropDownList("ddl_DetailType", Model.ParameterList, new { @class = "form-control select selectpicker" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div id="div_detaillength" @((Model.ParameterValueID == "TEXT" || Model.ParameterValueID == "DECIMAL" || Model.ParameterValueID == "NUMERIC") ? "" : "style=display:none;")>
                        <div class="col-xs-5">
                            <div class="form-group">
                                <br />
                                <label class="control-label" for="Length">@Resources.Request.lbl_Length</label>
                                <div class="input-group">
                                    <input type="text" id="DetailLength" class="form-control positive max-length text-center" maxlength="5" value="@Model.FormatDetail.FieldLength" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="div_detailprecition" @((Model.ParameterValueID == "DECIMAL") ? "" : "style=display:none;")>
                        <div class="col-xs-7">
                            <div class="form-group">
                                <br />
                                <label class="control-label" for="Precition">@Resources.Request.lbl_Precition</label>
                                <input type="text" id="detailPrecition" class="form-control positive max-length text-center" maxlength="5" value="@Model.FormatDetail.FieldPrecision" />
                            </div>
                        </div>
                    </div>
                    <div id="div_detailcatalog" @((Model.ParameterValueID == "LIST") ? "" : "style=display:none;")>
                        <div class="col-xs-12">
                            <div class="form-group">
                                <br />
                                <label class="control-label" for="ddl_list">@Resources.Request.lbl_CatalogList</label>
                                @Html.DropDownList("ddl_detaillist", Model.CatalogsList, new { @class = "form-control select" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <br />
                            <label class="control-label">@Resources.Request.lbl_Mandatory</label>
                            <br />
                            <div class="btn-group">
                                <button id="btn_YdMandatory" class="btn @(Model.FormatDetail.IsMandatory ? "btn-success sel" : "btn-default")" type="button">@Resources.Common.lbl_Yes</button>
                                <button id="btn_NdMandatory" class="btn @(Model.FormatDetail.IsMandatory ? "btn-default" : "btn-danger sel")" type="button">@Resources.Common.lbl_NO</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="form-group">
                            <br />
                            <label class="control-label" for="ddl_list">@Resources.Request.lbl_IsEnabled</label>
                            <br />
                            <div class="btn-group">
                                <button id="btn_YdEnable" class="btn @(Model.FormatDetail.Enabled ? "btn-success sel" : "btn-default")" type="button">@Resources.Common.lbl_Yes</button>
                                <button id="btn_NdEnable" class="btn @(Model.FormatDetail.Enabled ? "btn-default" : "btn-danger sel")" type="button">@Resources.Common.lbl_NO</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">@Resources.Common.btn_Back</button>
                @if (Model.FormatDetail.FormatGenericDetailID == 0)
                {
                    <button id="btn_ModalAddNewDetail" type="button" class="btn btn-info">@Resources.Common.btnAdd</button>
                }
                else
                {
                    <button id="btn_ModalAddNewDetail" type="button" class="btn btn-info">@Resources.Common.btn_Save</button>
                }
            </div>
        </div>
    </div>
</div>

WebSite/Areas/eRequest/Views/Formats/_Mo_New_PDFFieldDetailConfigure.cshtml
@model List<Core.Entities.FormatGenericDetailTemp>
<div id="mo_NewPDFFieldDetailConfiguration" class="modal fade" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-2" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title">@Resources.Request.H_SelectDetailsShow</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div id="tbl_phase_list">
                            <table class="table accesstable display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped" id="tbl_Rule_FielDetailConfiguration">
                                <thead>
                                    <tr class="font-size-sm bg-primary">
                                        <th width="20"></th>
                                        <th>@Resources.Request.lbl_DetailFields</th>
                                    </tr>
                                </thead>
                                <tbody class="ui-state-default sortable">
                                    @foreach (var item in Model)
                                    {
                                        <tr class="font-size-sm" data-fieldname="@item.ColumnName" data-formatgenericdetailID="@item.FormatGenericDetailID" data-formatgenericdetailtempid="@item.FormatGenericDetailTempID">
                                            <td>
                                                <label class="checkbox lobicheck lobicheck-rounded" style="margin-bottom: 20px; margin-left: 10px;">
                                                    <input id="@item.FormatGenericDetailTempID" @(item.IsCheck?"checked":"") class="item-check" type="checkbox">
                                                    <i class="p-relative"></i>
                                                </label>
                                            </td>
                                            <td>@item.ShowAs</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btn_back" data-dismiss="modal">@Resources.Common.btn_Back</button>
                <button id="btn_ModalSaveConfigurationDetailListPDF" type="button" class="btn btn-success">@Resources.Common.btn_Save</button>
            </div>
        </div>
    </div>
</div>

WebSite/Areas/eRequest/Views/Formats/_Tbl_Format_LoopRuleDetail.cshtml
@model WebSite.Areas.eRequest.Models.ViewModels.Formats.Tbl_Format_LoopRuleDetailModel
<div class="slider">
    <table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped margin-bottom-none" id="tbl_FormatsLoopsRulesDetail">
        <thead>
            <tr class="font-size-sm bg-primary">
                <th style="background-color: rgb(0, 136, 206) !important; color: whitesmoke !important;" class="text-center">#</th>
                <th style="background-color: rgb(0, 136, 206) !important; color: whitesmoke !important;">@Resources.Request.lbl_Rule</th>
                <th style="background-color: rgb(0, 136, 206) !important; color: whitesmoke !important;" width="230px">@Resources.Common.lbl_Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model._ListFormatLoopsRulesDetail_Temp)
            {
                <tr data-formatloopruletempid="@item.FormatLoopRuleTempID" data-seq="@item.Seq">
                    <td>@item.Seq</td>
                    <td>
                        @Html.Raw(item.Description)
                        @Html.Action("GetFormatsLoopsRulesDetailTableException", "Formats", new { FormatLoopRuleTempID = item.FormatLoopRuleTempID, TransactionID = Model.TransactionID, FormatID = Model.FormatID, Seq = item.Seq })
                    </td>
                    <td>
                        <button class="tbl_btn_addNewConditionRule btn btn-info" title="@Resources.Request.lbl_AddCondition" type="button"><span class="glyphicon glyphicon-plus"></span></button>
                        <button class="tbl_btn_addNewExceptionRule btn btn-warning" title="@Resources.Request.lbl_AddException" type="button"><span class="glyphicon glyphicon-plus"></span></button>
                        <button class="tbl_btn_EditRule btn btn-success" title="@Resources.Request.lbl_EditRule" type="button"><span class="fa fa-edit"></span></button>
                        <button class="tbl_btn_DeleteRule btn btn-danger" title="@Resources.Request.lbl_DeleteRule" type="button"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebSite/Areas/eRequest/Views/Formats/_Tbl_ResponsiblesResult.cshtml
@model List<Core.Entities.User>
<table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped margin-bottom-none">
    <thead>
        <tr class="font-size-sm bg-primary">
            <th>@Resources.Common.lbl_User</th>
            <th>@Resources.HR.Kiosk.lbl_eMail</th>
            <th width="60px"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName.Replace(".", " ")</td>
                <td>@item.eMail</td>
                <td>
                    <button class="addUserAccount btn btn-success"
                            data-useraccountid="@item.UserAccountID"
                            data-firstname="@item.FirstName"
                            data-email="@item.eMail">
                        @Resources.Common.btnAdd
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>