WebSite/Areas/MFG/Models/ViewModels/MoldFamilies/EditViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Areas.MFG.Models.ViewModels.MoldFamilies
{
    public class EditViewModel
    {
        public string Title { get; set; }
        public bool IsEdit { get; set; }
        public MoldFamily MoldFamilyObj { get; set; }
        public IEnumerable<SelectListItem> LensTypesList { get; set; }
        public List<LenType> LensOfFamily { get; set; }
        public string AuxiliarClass { get; set; }

        public EditViewModel()
        {
            Title = "";
            IsEdit = false;
            AuxiliarClass = "table_record";
            MoldFamilyObj = new MoldFamily();
            LensTypesList = new SelectList(new List<SelectListItem>());
            LensOfFamily = new List<LenType>();
        }
    }
}

WebSite/Areas/MFG/Models/ViewModels/MoldFamilies/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Entities;

namespace WebSite.Areas.MFG.Models.ViewModels.MoldFamilies
{
    public class IndexViewModel
    {
        public IEnumerable<SelectListItem> MoldFamiliesNamesList { get; set; }
        public IEnumerable<SelectListItem> LensTypesList { get; set; }
        public List<MoldFamily> MoldFamiliesRecordsList { get; set; }
        public string Message { get; set; }

        public IndexViewModel()
        {
            MoldFamiliesNamesList = new SelectList(new List<SelectListItem>());
            LensTypesList = new SelectList(new List<SelectListItem>());
            MoldFamiliesRecordsList = new List<MoldFamily>();
            Message = "";
        }
    }
}

WebSite/Areas/MFG/Controllers/MoldFamiliesController.cs
using Core.Service;
using Core.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Areas.MFG.Models.ViewModels.MoldFamilies;
using WebSite.Models;
using System.Data;
using System.IO;
using ClosedXML.Excel;

namespace WebSite.Areas.MFG.Controllers
{
    public class MoldFamiliesController : BaseController
    {
        public ActionResult Index(string Message)
        {
            IndexViewModel model = new IndexViewModel();
            try
            {
                var MoldFamiliesNamesList = vw_CatalogService.List("LensMoldFamilies", BaseGenericRequest);
                MoldFamiliesNamesList.Insert(0, new Catalog() { CatalogDetailID = 0, ValueID = Resources.Common.TagAll });
                model.MoldFamiliesNamesList = new SelectList(MoldFamiliesNamesList, "CatalogDetailID", "ValueID");

                var LensTypesList = LensTypesService.List(BaseGenericRequest);
                LensTypesList.Insert(0, new LenType() { LensTypeID = 0, LensTypeName = Resources.Common.TagAll });
                model.LensTypesList = new SelectList(LensTypesList, "LensTypeID", "LensTypeName");

                model.MoldFamiliesRecordsList = MoldFamilyLensTypesService.List(BaseGenericRequest);

                if (!String.IsNullOrEmpty(Message))
                    model.Message =Message;

            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
                return View(model);
            }

            return View(model);
        }

        public ActionResult New()
        {
            EditViewModel model = new EditViewModel();
            string viewPath = "~/Areas/MFG/Views/MoldFamilies/_Mo_NewEdit.cshtml";

            try
            {
                model.Title = Resources.MFG.MoldFamilies.title_NewMoldFamily;
                model.LensTypesList = new SelectList(LensTypesService.List(BaseGenericRequest), "LensTypeID", "LensTypeName");
                model.MoldFamilyObj.Enabled = true;
                model.AuxiliarClass = "neweditRecord";
            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }

            return Json(new
            {
                View = RenderRazorViewToString(viewPath, model)
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int MoldFamilyID)
        {
            EditViewModel model = new EditViewModel();
            string viewPath = "~/Areas/MFG/Views/MoldFamilies/_Mo_NewEdit.cshtml";

            try
            {
                int[] MoldFamilies = new int[] { MoldFamilyID };

                var MoldFamilyData = MoldFamilyLensTypesService.List(MoldFamilies, null, BaseGenericRequest).FirstOrDefault();
                model.IsEdit = true;
                model.AuxiliarClass = "neweditRecord";

                model.Title = Resources.MFG.MoldFamilies.title_NewMoldFamily;
                model.LensTypesList = new SelectList(LensTypesService.List(BaseGenericRequest), "LensTypeID", "LensTypeName");

                model.LensOfFamily = MoldFamilyLensTypesService.ListOfLens(MoldFamilyID, BaseGenericRequest);

                model.MoldFamilyObj.FamilyName = MoldFamilyData.FamilyName;
                model.MoldFamilyObj.Enabled = MoldFamilyData.Enabled;

            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }

            return Json(new
            {
                View = RenderRazorViewToString(viewPath, model)
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Search(int[] MoldFamiliesID, int[] MoldLensTypesID)
        {
            List<MoldFamily> list = new List<MoldFamily>();
            string ViewPath = "~/Areas/MFG/Views/MoldFamilies/_Tbl_MoldFamiliesRecords.cshtml";

            try
            {
                list = MoldFamilyLensTypesService.List(MoldFamiliesID, MoldLensTypesID, BaseGenericRequest);
            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }

            return Json(new
            {
                View = RenderRazorViewToString(ViewPath, list)
            }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult LoadLensOfFamily(int MoldFamilyID, int?[] MoldLensTypeIDs)
        {
            EditViewModel model = new EditViewModel();
            string ViewPath = "~/Areas/MFG/Views/MoldFamilies/_Tbl_LenTypes.cshtml";

            try
            {
                model.LensOfFamily = MoldFamilyLensTypesService.ListOfLens(MoldFamilyID, MoldLensTypeIDs, BaseGenericRequest);
            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
            }

            return Json(new
            {
                View = RenderRazorViewToString(ViewPath, model)
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Save(int? MoldFamilyID, string MoldFamilyName, string LensTypeIDs, bool Enabled)
        {
            GenericReturn result = new GenericReturn();

            try
            {
                if (MoldFamilyID == null)
                    result = MoldFamilyLensTypesService.Save(MoldFamilyName, LensTypeIDs, Enabled, BaseGenericRequest);
                else
                    result = MoldFamilyLensTypesService.Update(MoldFamilyID, MoldFamilyName, LensTypeIDs, Enabled, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString()
            }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult DeleteMoldFamily(int MoldFamilyID)
        {
            GenericReturn result = new GenericReturn();

            try
            {
                result = CatalogDetailService.Delete(MoldFamilyID, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                ErrorCode = result.ErrorCode,
                ErrorMessage = result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteLenTypeFromFamily(int MoldFamilyLenTypeID)
        {
            GenericReturn result = new GenericReturn();

            try
            {
                result = MoldFamilyLensTypesService.Delete(MoldFamilyLenTypeID, BaseGenericRequest);
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                ErrorCode = result.ErrorCode,
                ErrorMessage = result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetMoldFamiliesList()
        {
            IEnumerable<SelectListItem> list = new SelectList(new List<SelectListItem>());
            GenericReturn result = new GenericReturn();

            try
            {
                var MoldFamiliesNamesList = vw_CatalogService.List("LensMoldFamilies", BaseGenericRequest);
                MoldFamiliesNamesList.Insert(0, new Catalog() { CatalogDetailID = 0, ValueID = Resources.Common.TagAll });
                list = new SelectList(MoldFamiliesNamesList, "CatalogDetailID", "ValueID");


                if (list != null)
                {
                    if (list.Count() == 1)
                    {
                        var AuxList = new List<Catalog>();
                        AuxList.Insert(0, new Catalog() { CatalogDetailID = 0, ValueID = Resources.Common.TagAll });
                        list = new SelectList(AuxList, "CatalogDetailID", "ValueID");
                    }

                    result.ErrorCode = 0;
                }
            }
            catch (Exception ex)
            {
                result.ErrorCode = 99;
                result.ErrorMessage = ex.Message;
            }

            return Json(new
            {
                result.ErrorCode,
                result.ErrorMessage,
                notifyType = result.ErrorCode == 0 ? StaticModels.NotifyType.success.ToString() : StaticModels.NotifyType.error.ToString(),
                list
            }, JsonRequestBehavior.AllowGet);
        }


        #region Excel
        public ActionResult UploadExcel()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase file)
        {           
            IndexViewModel model = new IndexViewModel();
            GenericReturn result = new GenericReturn();

            TimeSpan t = (DateTime.UtcNow - new DateTime(1970, 1, 1));
            var AuxiliarName = (int)t.TotalSeconds;

            DataTable dt = new DataTable();
            //Checking file content length and Extension must be .xlsx  
            if (file != null && file.ContentLength > 0 && Path.GetExtension(file.FileName).ToLower() == ".xlsx")
            {
                string path = Path.Combine(Server.MapPath("~/Files/Temp/MoldFamiliesExcelUpdate"), Path.GetFileName(file.FileName.ToLower().Replace(".xlsx", "_" + AuxiliarName + ".xlsx")));

WebSite/Areas/MFG/Views/MoldFamilies/Index.cshtml
@model WebSite.Areas.MFG.Models.ViewModels.MoldFamilies.IndexViewModel
<div class="content-frame">
    <div class="content-frame-top">
        <div class="row">
            <div class="col-sm-9">
                <div class="page-title">
                    <h2 class="margin-none">@Resources.MFG.MoldFamilies.title_MoldFamiliesList</h2>
                </div>
            </div>

            <div class="col-sm-5" style="text-align:right; display:none">
                @using (Html.BeginForm("UploadExcel", "MoldFamilies", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @*<label>@Resources.MFG.MoldFamilies.btn_UpdateFromExcel:</label>*@
                    <div class="col-sm-5">
                        <input type="file" id="file" name="file" />
                    </div>
                    <div class="col-sm-7">
                        <input type="submit" id="submit_Excelinfo" class="btn btn btn-info" value="@Resources.MFG.MoldFamilies.btn_UpdateFromExcel" />
                    </div>
                }
            </div>
            <div class="col-sm-2">
                <button id="btn_excel" class="btn btn btn-info pull-right">@Resources.MFG.MoldFamilies.btn_UpdateFromExcel</button>
            </div>

            <div class="col-sm-1">
                <div class="pull-right">
                    <button id="btn_New" class="btn btn btn-success">
                        <span class="fa fa-plus-circle"></span>
                        @Resources.Common.btn_New
                    </button>
                </div>
            </div>

        </div>
    </div>
    <div class="content-frame-body content-frame-body-all">
        <div class="panel panel-primary">
            <div class="panel-heading ui-draggable-handle">
                <h3 class="panel-title">@Resources.Common.lbl_Filters</h3>
                <ul class="panel-controls">
                    <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-3 col-md-3">
                        <label>@Resources.MFG.MoldFamilies.lbl_FamilyName</label>
                        @Html.DropDownList("ddl_FamilyNames", Model.MoldFamiliesNamesList, new { @class = "form-control selectpicker filters", @multiple = "multiple", @data_live_search = "true" })
                    </div>
                    <div class="col-xs-3 col-md-3">
                        <label>@Resources.MFG.MoldFamilies.lbl_LenTypes</label>
                        @Html.DropDownList("ddl_LensTypes", Model.LensTypesList, new { @class = "form-control selectpicker filters", @multiple = "multiple" ,@data_live_search="true"})
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3 col-md-3 panel-footer text-right">
                <button id="btn_Search" class="btn btn-info">@Resources.Common.search</button>
            </div>
        </div>

        <div class="panel panel-info">
            <div id="div_MoldFamiliesRecordsTable">
                @Html.Partial("_Tbl_MoldFamiliesRecords", Model.MoldFamiliesRecordsList)
            </div>
        </div>
    </div>
</div>

<div id="_mo_NewEdit">

</div>

@section Styles
{
    <link href="~/Content/PLUGINS/bootstrap/bootstrap.min.css" rel="stylesheet" />
}

@section Scripts
{
    @Scripts.Render("~/bundles/bootstrap-select")
    <script src="~/Scripts/PLUGINS/maxlength/bootstrap-maxlength.min.js"></script>
    <script src="~/Scripts/MFG/MoldFamilies/Index.js?v20190924" charset="utf-8"></script>


    <script type="text/javascript">
        $(document).ready(function () {

            var LangResources = {
                msg_SelectLensType: "@Html.Raw(Resources.MFG.MoldFamilies.msg_SelectLensType)",
                msg_LenTypeAlreadyAssigned: "@Html.Raw(Resources.MFG.MoldFamilies.msg_LenTypeAlreadyAssigned)",
                msg_MoldFamilyDeleted: "@Html.Raw(Resources.MFG.MoldFamilies.msg_MoldFamilyDeleted)",
                msg_DeleteMoldFamilyRecordConfirm: "@Html.Raw(Resources.MFG.MoldFamilies.msg_DeleteMoldFamilyRecordConfirm)",
                msg_DeleteLenTypeRecordConfirm: "@Html.Raw(Resources.MFG.MoldFamilies.msg_DeleteLenTypeRecordConfirm)",
                msg_LenTypesRequiredInTable: "@Html.Raw(Resources.MFG.MoldFamilies.msg_LenTypesRequiredInTable)"
            };

            IndexInit(LangResources);
        });
    </script>
}

@Html.Hidden("ExcelImportMessage", Model.Message)

WebSite/Areas/MFG/Views/MoldFamilies/_Mo_NewEdit.cshtml
@model WebSite.Areas.MFG.Models.ViewModels.MoldFamilies.EditViewModel
<div id="mo_NewEditMoldFamily" class="modal fade" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false" style="z-index:9">
    <div class="col-sm-4"></div>
    <div class="modal-dialog col-sm-4" style="text-align:center">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close close-2" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title">@Model.Title</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-3" style="text-align:right">
                        <label>@Resources.MFG.MoldFamilies.lbl_FamilyName</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBox("txt_mo_FamilyName", Model.MoldFamilyObj.FamilyName, new { @class = "form-control selectpicker max-length", @maxlength = "50" })
                    </div>
                </div>

                <br />
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3" style="text-align:right">
                            <label class="control-label">@Resources.MFG.MachineSetups.lbl_Enable</label>
                        </div>
                        <div class="col-sm-9" style="text-align:left">
                            <label class="switch switch-small col-sm-7">
                                <input type="checkbox" id="chk_Enabled" checked="@Model.MoldFamilyObj.Enabled" />
                                <span> &nbsp;</span>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-3" style="text-align:right">
                        <label>@Resources.MFG.MoldFamilies.lbl_LenTypes</label>
                    </div>
                    <div class="col-sm-6">
                        @Html.DropDownList("txt_mo_LenTypes", Model.LensTypesList, new { @class = "form-control selectpicker", data_live_search = "true" })
                    </div>
                    <div class="col-sm-3 pull-right">
                        <button id="addLenToFamily" class="btn btn-info pull-right" style="background-color:dodgerblue !important; width:90%">@Resources.Common.btnAdd</button>
                    </div>
                </div>

                <br />
                <div class="row">
                    <div class="col-sm-12">
                        @Html.Partial("_Tbl_LenTypes", Model)
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="btn_back" data-dismiss="modal">@Resources.Common.btn_Back</button>
                @if (Model.IsEdit)
                {
                    <button id="btn_ModalSaveEditedMoldFamily" type="button" class="btn btn-info">@Resources.Common.btn_Save</button>
                }
                else
                {
                    <button id="btn_ModalSaveNewMoldFamily" type="button" class="btn btn-info">@Resources.Common.btn_Save</button>
                }
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>

</div>

@Html.Hidden("MoldFamilyID", Model.MoldFamilyObj.MoldFamilyID)

WebSite/Areas/MFG/Views/MoldFamilies/_Tbl_LenTypes.cshtml
@model WebSite.Areas.MFG.Models.ViewModels.MoldFamilies.EditViewModel
<div id="sliderID" class="slider">
    <table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped" id="table_LensTypes">
        <thead>
            <tr class="font-size-sm bg-primary">
                <th class="text_center">@Resources.MFG.MoldFamilies.lbl_LensTypes</th>
                <th style="width:5%">@Resources.Common.lbl_Options</th>
            </tr>
        </thead>
        <tbody class="sortable">
            @foreach (var item in Model.LensOfFamily)
            {
                <tr data-entityid="@item.LensTypeID" class="LenTypesRow @Model.AuxiliarClass" data-moldfamilylenid="@item.MoldFamilyLensTypeID">
                    <td class="text_center">@item.LensTypeName</td>
                    <td text-align:center">
                        <button class="btn btn-danger delete-lentype-record"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebSite/Areas/MFG/Views/MoldFamilies/_Tbl_MoldFamiliesRecords.cshtml
@model List<Core.Entities.MoldFamily>
<div class="panel-body">
    <table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped" id="table_MoldFamilies">
        <thead>
            <tr class="font-size-sm bg-primary">
                <th width="5%"></th>
                <th>@Resources.MFG.MoldFamilies.lbl_FamilyName</th>
                <th>@Resources.MFG.MoldFamilies.lbl_Lens</th>
                <th>@Resources.MFG.MachineSetups.lbl_Enabled</th>
                <th style="width:5%">@Resources.Common.lbl_Options</th>
            </tr>
        </thead>
        <tbody class="sortable">
            @foreach (var item in Model)
            {
                <tr data-entityid="@item.MoldFamilyID">
                    <td class="details-control" width="5%"></td>
                    <td>@item.FamilyName</td>
                    <td>@item.Lens</td>
                    <td>@item.Enabled</td>
                    <td style="width:15%; text-align:center">
                        <button class="btn btn-success text-primary edit-moldfamily-record"><span class="fa fa-lg fa-edit" style="color:white !important"></span></button>
                        <button class="btn btn-danger delete-moldfamily-record"><span class="glyphicon glyphicon-trash"></span></button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>