WebSite/Areas/eRequest/Controllers/RequestController.cs
using Core.Entities;
using Core.Entities.SQL_DataType;
using Core.Entities.Utilities;
using Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebSite.Areas.eRequest.Models.ViewModels.Request;
using WebSite.Filters;
using WebSite.Models;
using WebSite.Utilities;
using static WebSite.Models.StaticModels;

namespace WebSite.Areas.eRequest.Controllers
{
    public class RequestController : BaseController
    {
        // GET: eRequest/Request
        [SecurityFilter]
        public ActionResult Index(int? RequestID)
        {
            var model = new IndexViewModel();

            try
            {
                // Listados para los combos
                var UserAccess = RequestService.GetUserAccessToeRequest(BaseGenericRequest);
                model.AllowFullAccess = UserAccess.FirstOrDefault().AllowFullAccess;
                model.AllowEdit = UserAccess.FirstOrDefault().AllowEdit;
                model.AllowCancel = UserAccess.FirstOrDefault().AllowCancel;
                model.AllowCreateReq = UserAccess.FirstOrDefault().AllowCreateReq;
                model.AllowApproveReq = UserAccess.FirstOrDefault().AllowApproveReq;
                model.FacilityList = new SelectList(RequestService.GetFacility(BaseGenericRequest, true, Resources.Common.chsn_SelectOption), "FacilityID", "FacilityName");
                model.FormatList = new SelectList(RequestService.GetFormat4User(BaseGenericRequest), "FormatID", "FormatName");
                model.DepartmentList = new SelectList(DepartmentService.List(null, null, true, BaseGenericRequest.FacilityID, BaseGenericRequest.UserID, BaseGenericRequest.CultureID, false), "DepartmentID", "DepartmentName");
                model.DateTypeList = new SelectList(vw_CatalogService.List("eReq_DateType", BaseGenericRequest), "CatalogDetailID", "DisplayText");
                model.StatusList = new SelectList(vw_CatalogService.List("eReq_RequestStatus", BaseGenericRequest), "CatalogDetailID", "DisplayText");
                model.RequestDefaultStatus = MiscellaneousService.Param_GetValue(VARG_FacilityID, "eReq_RequestDefaultStatus", "0");
                model.UserFacilitiesList = new SelectList(UserService.GetFacilities(VARG_UserID, VARG_FacilityID, VARG_CultureID), "FacilityID", "FacilityName");
                if (RequestID != null)
                {
                    model.RequestList = RequestService.RequestList(RequestID, null, null, null, null, null, null, null, null, BaseGenericRequest);
                }
                else
                {
                    model.RequestList = RequestService.RequestList(null, null, null, null, null, null, null, null, null, BaseGenericRequest);
                }
                //model.ApprovalStatusID = vw_CatalogService.List("eReq_RequestStatus", BaseGenericRequest).Where(v => v.ValueID == "Approval").FirstOrDefault().CatalogDetailID;
            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
                return View(model);
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(model);
            }

            return View(model);
        }

        public ActionResult SearchRequest(string FormatIDs, int? Folio, string DepartmentIDs, string StatusIDs, string FacilityIDs, int? DateTypeID, DateTime? StartDate, DateTime? EndDate)
        {
            IndexViewModel model = new IndexViewModel();
            string viewPath = "~/Areas/eRequest/Views/Request/_Tbl_Requests.cshtml";

            try
            {
                var UserAccess = RequestService.GetUserAccessToeRequest(BaseGenericRequest);
                model.AllowFullAccess = UserAccess.FirstOrDefault().AllowFullAccess;
                model.AllowEdit = UserAccess.FirstOrDefault().AllowEdit;
                model.AllowCancel = UserAccess.FirstOrDefault().AllowCancel;
                model.AllowPdf = UserAccess.FirstOrDefault().AllowViewPdf;
                model.AllowViewLog = UserAccess.FirstOrDefault().AllowViewLog;
                model.RequestList = RequestService.RequestList(null, FormatIDs, Folio, DepartmentIDs, StatusIDs, FacilityIDs, DateTypeID, StartDate, EndDate, BaseGenericRequest);

            }
            catch (Exception e)
            {
                ViewBag.Exception = e.Message;
                return View(model);
            }

            return PartialView(viewPath, model);
        }

        public JsonResult GetRequestByFacility(int FacilityID)
        {
            var list = RequestService.GetFormat4User(new GenericRequest() { FacilityID = FacilityID, UserID = BaseGenericRequest.UserID, CultureID = BaseGenericRequest.CultureID });
            list.Insert(0, new FormatsEntity() { FormatID = 0, FormatName = Resources.Common.chsn_SelectOption });
            return Json(list.Select(s => new { value = s.FormatID, text = s.FormatName }), JsonRequestBehavior.AllowGet);
        }

        #region List

        public ActionResult GetDetail(int RequestID, int FormatID, bool ViewReadOnly)
        {
            try
            {
                List<TableAdditionalFields> result = null;
                List<RequestGenericDetail_tb> resultvalues = null;
                JavaScriptSerializer serializer = new JavaScriptSerializer();

                result = Core.Services.TableAdditionalFieldService.ListDetail(RequestID, FormatID, BaseGenericRequest);
                resultvalues = RequestService.RequestsGenericDetailListTable(RequestID, BaseGenericRequest);

                if (result != null && result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSON))
                        {
                            item.CatalogContext = serializer.Deserialize<List<Catalog>>(item.CatalogJSON);
                            item.CatalogContext.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }
                if (resultvalues != null && resultvalues.Count > 0)
                {
                    foreach (var item in resultvalues)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSONConcept))
                        {
                            item.CatalogContextConcept = serializer.Deserialize<List<Catalog>>(item.CatalogJSONConcept);
                            item.CatalogContextConcept.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                        if (!string.IsNullOrEmpty(item.CatalogJSONReference1))
                        {
                            item.CatalogContextReference1 = serializer.Deserialize<List<Catalog>>(item.CatalogJSONReference1);
                            item.CatalogContextReference1.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                        if (!string.IsNullOrEmpty(item.CatalogJSONReference2))
                        {
                            item.CatalogContextReference2 = serializer.Deserialize<List<Catalog>>(item.CatalogJSONReference2);
                            item.CatalogContextReference2.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                        if (!string.IsNullOrEmpty(item.CatalogJSONReference3))
                        {
                            item.CatalogContextReference3 = serializer.Deserialize<List<Catalog>>(item.CatalogJSONReference3);
                            item.CatalogContextReference3.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                        if (!string.IsNullOrEmpty(item.CatalogJSONReference4))
                        {
                            item.CatalogContextReference4 = serializer.Deserialize<List<Catalog>>(item.CatalogJSONReference4);
                            item.CatalogContextReference4.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                        if (!string.IsNullOrEmpty(item.CatalogJSONReference5))
                        {
                            item.CatalogContextReference5 = serializer.Deserialize<List<Catalog>>(item.CatalogJSONReference5);
                            item.CatalogContextReference5.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }
                var model = new AdditionalFieldsDescriptionViewModel
                {
                    CollectionAdditionalFields = result,
                    CollectionAdditionalFieldsTable = resultvalues,
                    ViewReadOnly = ViewReadOnly,
                    ReferenceID = RequestID
                };
                if (Request.IsAjaxRequest())
                {
                    return PartialView("~/Areas/eRequest/Views/Request/_AdditionalFieldsDescriptionView.cshtml", model);
                }
                return PartialView("~/Areas/eRequest/Views/Request/_AdditionalFieldsDescriptionView.cshtml", model);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ErrorCode = 99,
                    ErrorMessage = e.Message,
                    Title = "",
                    notifyType = NotifyType.error.ToString()
                }, JsonRequestBehavior.AllowGet);
                throw;
            }

        }

        public JsonResult NextSeq(int RequestLoopFlowID)
        {
            GenericReturn result = new GenericReturn();
            try
            {
                result = RequestService.SeqValidate(RequestLoopFlowID, BaseGenericRequest);
            }

WebSite/Controllers/AdditionalFieldsController.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebSite.Filters;
using WebSite.Models.ViewModels;
using WebSite.Utilities;
using static WebSite.Models.StaticModels;

namespace WebSite.Controllers
{
    [SessionExpire]
    public class AdditionalFieldsController : BaseController
    {
        public ActionResult Get(int ReferenceID, string ModuleName, bool ViewReadOnly)
        {
            try
            {
                List<TableAdditionalFields> result = null;
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                result = Core.Services.TableAdditionalFieldService.List(ReferenceID, ModuleName, BaseGenericRequest);

                if (result != null && result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSON))
                        {
                            item.CatalogContext = serializer.Deserialize<List<Catalog>>(item.CatalogJSON);
                            item.CatalogContext.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }

                var model = new AdditionalFieldsViewModel
                {
                    CollectionAdditionalFields = result,
                    ViewReadOnly = ViewReadOnly,
                    ReferenceID = ReferenceID
                };
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_AdditionalFieldsView", model);
                }
                return PartialView("_AdditionalFieldsView", model);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ErrorCode = 99,
                    ErrorMessage = e.Message,
                    Title = "",
                    notifyType = NotifyType.error.ToString()
                }, JsonRequestBehavior.AllowGet);
                throw;
            }

        }
        public ActionResult GetConfiguration(int ReferenceID, int FormatID, string ModuleName, bool ViewReadOnly)
        {
            try
            {
                List<TableAdditionalFields> result = null;
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                result = Core.Services.TableAdditionalFieldService.ListConfiguration(ReferenceID, FormatID, ModuleName, BaseGenericRequest);

                if (result != null && result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSON))
                        {
                            item.CatalogContext = serializer.Deserialize<List<Catalog>>(item.CatalogJSON);
                            item.CatalogContext.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }

                var model = new AdditionalFieldsViewModel
                {
                    CollectionAdditionalFields = result,
                    ViewReadOnly = ViewReadOnly,
                    ReferenceID = ReferenceID
                };
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_AdditionalFieldsView", model);
                }
                return PartialView("_AdditionalFieldsView", model);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ErrorCode = 99,
                    ErrorMessage = e.Message,
                    Title = "",
                    notifyType = NotifyType.error.ToString()
                }, JsonRequestBehavior.AllowGet);
                throw;
            }

        }

        public ActionResult GetListIndex(int ReferenceID, int FormatID, string ModuleName, bool ViewReadOnly)
        {
            try
            {
                List<TableAdditionalFields> result = null;
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                result = Core.Services.TableAdditionalFieldService.ListConfiguration(ReferenceID, FormatID, ModuleName, BaseGenericRequest);

                if (result != null && result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSON))
                        {
                            item.CatalogContext = serializer.Deserialize<List<Catalog>>(item.CatalogJSON);
                            item.CatalogContext.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }

                var model = new AdditionalFieldsViewModel
                {
                    CollectionAdditionalFields = result,
                    ViewReadOnly = ViewReadOnly,
                    ReferenceID = ReferenceID
                };
                
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_AdditionalFieldsIndexView", model);
                }
                return PartialView("_AdditionalFieldsIndexView", model);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ErrorCode = 99,
                    ErrorMessage = e.Message,
                    Title = "",
                    notifyType = NotifyType.error.ToString()
                }, JsonRequestBehavior.AllowGet);
                throw;
            }

        }

        public ActionResult GetColumn(int ReferenceID, string ModuleName, string ColumnName, bool ViewReadOnly)
        {
            try
            {
                List<TableAdditionalFields> result = null;
                JavaScriptSerializer serializer = new JavaScriptSerializer();
                result = Core.Services.TableAdditionalFieldService.List4Column(ReferenceID, ModuleName, ColumnName, BaseGenericRequest);

                if (result != null && result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        if (!string.IsNullOrEmpty(item.CatalogJSON))
                        {
                            item.CatalogContext = serializer.Deserialize<List<Catalog>>(item.CatalogJSON);
                            item.CatalogContext.Insert(0, new Catalog { CatalogDetailID = 0, DisplayText = "" });
                        }
                    }
                }

                var model = new AdditionalFieldsViewModel
                {
                    CollectionAdditionalFields = result,
                    ViewReadOnly = ViewReadOnly,
                    ReferenceID = ReferenceID
                };
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_AdditionalFieldView", model);
                }
                return PartialView("_AdditionalFieldView", model);
            }
            catch (Exception e)
            {
                return Json(new
                {
                    ErrorCode = 99,
                    ErrorMessage = e.Message,
                    Title = "",
                    notifyType = NotifyType.error.ToString()
                }, JsonRequestBehavior.AllowGet);
                throw;
            }

        }
    }
}

WebSite/Areas/eRequest/Views/Request/Create.cshtml
@model WebSite.Areas.eRequest.Models.ViewModels.Request.CreateViewModel
<div class="content-frame">
    <div class="content-frame-top">
        <div class="page-title">

            @if (Model.RequestID != 0)
            {
                if (Model.ViewReadOnly)
                {
                    <h2 class="remove-margins"> @Resources.Request.lbl_Folio : <span class="Format-Title">@Model.Folio</span></h2>
                }
                else
                {
                    <h2 class="remove-margins"> @Resources.Request.lbl_EditFolio : <span class="Format-Title">@Model.Folio</span></h2>
                }

            }
            else
            {
                <h2 class="remove-margins"> @Resources.Request.H_CreateRequest : <span class="Format-Title">@Model.EntityFormat.FormatName</span> <span class="Format-Title">@Model.Folio</span> </h2>
            }
        </div>
        <div class="pull-right">
            @if (Model.ViewReadOnly)
            {
                <button class="btn btn-primary btn-cancel-back" id="btnBack" title="@Resources.Common.btn_Back"><span class="fa fa-arrow-left"></span>@Resources.Common.btn_Back</button>
            }
            else
            {
                <button class="btn btn-danger btn-cancel-back" id="btnCancel" title="@Resources.Common.btnCancel"><span class="fa fa-ban"></span>@Resources.Common.btnCancel</button>
                if (Model.RequestID != 0)
                {
                    <button id="btn_SaveRequest" class="btn btn-success @Model.Btn_Save_ID" title="@Resources.Common.lbl_Edit"><span class="fa fa-floppy-o"></span>@Resources.Common.lbl_Edit</button>
                }
                else
                {
                    <button id="btn_SaveRequest" class="btn btn-success @Model.Btn_Save_ID" title="@Resources.Common.btn_Create"><span class="fa fa-plus-circle"></span>@Resources.Common.btn_Create </button>
                }
            }
        </div>
    </div>

    <div class="content-frame-body content-frame-body-all">
        <div class="panel panel-primary">
            <div class="panel-heading ui-draggable-handle">
                <h2 class="panel-title">
                    @Resources.Request.lbl_General
                </h2>
            </div>

            <div class="panel-body">
                <form id="create-form" class="lobi-form">
                    <fieldset>
                        <div class="row">
                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "Facility").IsVisible)
                            {
                                <div class="col-xs-12 col-sm-4 col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="MaterialOwned">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "Facility").FieldName)</label>
                                        @Html.DropDownList("MaterialOwned", Model.FacilityList, htmlAttributes: new { @class = "form-control select", @Model.disabled })
                                    </div>
                                </div>
                            }
                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "RequestDate").IsVisible)
                            {
                                <div class="col-xs-12 col-sm-4 col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="txt_RequestDate">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "RequestDate").FieldName)</label>
                                        <input type="text" id="txt_RequestDate" class="form-control customdatepicker datetimepicker" name="txt_RequestDate"
                                               style="text-align: center;border-radius: 4px;" value="@Model.RequestDate" disabled>
                                    </div>
                                </div>
                            }
                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "Department").IsVisible)
                            {
                                <div class="col-xs-12 col-sm-4 col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="DepeartmentID">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "Department").FieldName)</label>
                                        @Html.DropDownList("DepeartmentID", Model.DepartmentList, htmlAttributes: new { @class = "form-control select", title = Resources.Common.chsn_SelectOption })
                                    </div>
                                </div>
                            }
                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "Format").IsVisible)
                            {
                                <div class="col-xs-12 col-sm-4 col-md-3">
                                    <div class="form-group">
                                        <label class="control-label" for="DepeartmentID">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "Format").FieldName)</label>
                                        @Html.DropDownList("FormatID", Model.FormatList, htmlAttributes: new { @class = "form-control select", @Model.disabled, title = Resources.Common.chsn_SelectOption })
                                    </div>
                                </div>
                            }

                            @Html.Action("GetConfiguration", "AdditionalFields", new { Area = "", ReferenceID = Model.RequestID, FormatID = Model.FormatID, ModuleName = "Requests", ViewReadOnly = @Model.ViewReadOnly })

                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "Concept").IsVisible)
                            {
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="Justification">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "Concept").FieldName)</label>
                                        <textarea type="text" id="Justification" name="Justification" maxlength="500" rows="3" class="max-lenght form-control" style="resize: none; @Model.disabled" @Model.disabled>@Model.ConceptValue</textarea>
                                    </div>
                                </div>
                            }
                            @if (Model.EntityFields != null && Model.EntityFields.FirstOrDefault(w => w.ValueID == "Specification").IsVisible)
                            {
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label" for="Specification">@(Model.EntityFields.FirstOrDefault(w => w.ValueID == "Specification").FieldName)</label>
                                        <textarea type="text" id="Specification" name="Specification" maxlength="500" rows="3" class="max-lenght form-control" style="resize: none;" @Model.disabled>@Model.SpecificationValue</textarea>
                                    </div>
                                </div>
                            }

                        </div>
                    </fieldset>
                </form>
            </div>

        </div>

        @if (Model.EntityFormat.HasDetail)
        {
            <div class="panel panel-primary">
                <div class="panel-heading ui-draggable-handle">
                    <h2 class="panel-title">
                        @Resources.Request.lbl_Detail
                    </h2>
                </div>
                <div class="panel-body">
                    <form id="create-form" class="lobi-form">
                        <fieldset>
                            <div class="row">
                            @Html.Action("GetDetail", "Request", new { Area = "", RequestID = Model.RequestID, FormatID = Model.FormatID, ViewReadOnly = @Model.ViewReadOnly })
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        }
        @if (Model.EntityFormat.HasAttachment)
        {
            <div class="panel panel-primary">
                <div class="panel-heading ui-draggable-handle">
                    <h2 class="panel-title">
                        @Resources.Request.lbl_Attachments
                    </h2>
                </div>
                <div class="panel-body">
                    @if (!Model.ViewReadOnly)
                    {
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="border-dashed-2">
                                    <form action="~/Attachments/SaveDropzoneJsUploadedFiles" class="form-dropzone form-dropzone-Opportunity needsclick dz-clickable h-150">
                                        @Html.Hidden("ReferenceID", Model.TempAttachmentID)
                                        @Html.Hidden("AttachmentType", "TEMPID")
                                        <div class="dz-message center-content padding-top-10">
                                            <img src="~/Content/img/UploadCloud.png" />
                                        </div>
                                        <div class="center-content">
                                            @Resources.Common.lbl_Dropfiles
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }

                    <div class="row">
                        <div class="col-xs-12">
                            <div id="div_AttachmentsTable">
                                @Html.Partial("_AttachmentsTable", Model.FormatMediaList)
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        }
        <div class="pull-right">
            @if (Model.ViewReadOnly)
            {
                <button class="btn btn-primary btn-cancel-back" title="@Resources.Common.btn_Back"><span class="fa fa-arrow-left"> @Resources.Common.btn_Back </span></button>
            }
            else
            {
                <button class="btn btn-danger btn-cancel-back" title="@Resources.Common.btnCancel"><span class="fa fa-ban"> @Resources.Common.btnCancel </span></button>
                if (Model.RequestID != 0)
                {
                    <button class="btn btn-success @Model.Btn_Save_ID" title="@Resources.Common.lbl_Edit"><span class="fa fa-floppy-o"> @Resources.Common.lbl_Edit </span></button>
                }
                else
                {
                    <button class="btn btn-success @Model.Btn_Save_ID" title="@Resources.Common.btn_Create"><span class="fa fa-plus-circle"> @Resources.Common.btn_Create </span></button>
                }
            }
            <br />
            <br />
        </div>
    </div>
    @Html.Hidden("NewEdit_RequestID", Model.RequestID)

</div>

@Html.Partial("_ImageResourceModal")


@section Styles
    {
    <link href="~/Content/PLUGINS/dropzone/dropzone.css" rel="stylesheet" />
    <link href="~/Content/PLUGINS/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/PLUGINS/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/PLUGINS/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/PLUGINS/moment/moment.min.js"></script>
    <script src="~/Scripts/PLUGINS/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/PLUGINS/bootstrap/bootstrap-select.js" charset="utf-8"></script>
    <script src="~/Scripts/PLUGINS/maxlength/bootstrap-maxlength.min.js"></script>
    <script src="~/Scripts/PLUGINS/bootstrap/bootstrap-select.js"></script>
    <script src="~/Scripts/PLUGINS/summernote/summernote.js"></script>
    <script src="~/Scripts/PLUGINS/dropzone/dropzone.min.js"></script>
    <script src="~/Scripts/eRequest/Request/Index.js" charset="utf-8"></script>
    <script type="text/javascript" src="~/Scripts/eRequest/Request/Create.js?v20200908"></script>

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {

            var LangResources = {
                msg_CancelReqCreate: "@Html.Raw(Resources.Request.msg_CancelReqCreate)",
                chsn_SelectOption: "@Html.Raw(Resources.Common.chsn_SelectOption)",
                msg_CreateReqConfirmation: "@Html.Raw(Resources.Request.msg_CreateReqConfirmation)",
            };

            CreateInit(LangResources);
        });
    </script>
}

WebSite/Areas/eRequest/Views/Request/_tbl_RequestApprovalLog.cshtml
@model List<Core.Entities.RequestApprovalLog>
<div class="slider" style="width:100%;">

    <table class="table display table-condensed table-strdisplay table table-striped table-bordered table-condensed-xs margin-noneiped margin-bottom-none">
        <thead>
            <tr class="font-size-sm bg-primary">
                <th>Tipo de movimiento</th>
                <th>Comentario</th>
                <th>@Resources.Common.gvH_UpdatedBy</th>
                <th>@Resources.Common.lbl_Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.ApprovedStatusName</td>
                <td>@item.Commets</td>
                <td>@item.UserFullName</td>
                <td>@item.DateAddedFormat</td>
            </tr>
            }
        </tbody>
    </table>
</div>